/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.viandwi24.asteroidguard;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;

import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author viandwi24
 */
public class AsteroidInformation extends javax.swing.JFrame {
    JSONObject asteroid;

    /**
     * Creates new form AsteroidInformation
     */
    public AsteroidInformation(JSONObject asteroid) {
        this.asteroid = asteroid;
        initComponents();
        animateComponents();
        initInformation();
    }

    public void initInformation() {
        // set name of asteroid
        lblAsteroidName.setText(asteroid.getString("name"));
        lblDetailName.setText("Name : " + asteroid.getString("name"));
        lblDetailMagnitude.setText("Magnitude : " + asteroid.getFloat("absolute_magnitude_h") + "");
        lblDetailDiameter.setText("Diameter : " + asteroid.getJSONObject("estimated_diameter").getJSONObject("kilometers").getFloat("estimated_diameter_min") + "");

        // 
        JSONArray close_approach_data = asteroid.getJSONArray("close_approach_data");
        for (int i = 0; i < close_approach_data.length(); i++) {
            JSONObject approach = close_approach_data.getJSONObject(i);
            JSONObject relative_velocity = approach.getJSONObject("relative_velocity");
            JSONObject miss_distance = approach.getJSONObject("miss_distance");
            String orbiting_body = approach.getString("orbiting_body");
            lblAsteroidDistance.setText(miss_distance.getFloat("kilometers") + " KM");
            lblDetailOrbit.setText("Orbitting Body : " + orbiting_body);
            lblDetailVelocity.setText("Velocity : " + relative_velocity.getFloat("kilometers_per_second") + " KM/s");
        }
    }
    
    public void animateComponents() {
        // animate img planet1 bounce top and down
        Timer planet1Animation = createAnimationPlanet(this.ImgEarth);
        Timer planet2Animation = createAnimationPlanet(this.ImgAsteroid);
    }
    
    public Timer createAnimationPlanet(JLabel planet) {
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask() {
            // rand true or false
            boolean up = Math.random() < 0.5;
            boolean left = Math.random() < 0.5;
            int initialY = planet.getY();
            int initialX = planet.getX();
            int maxAnimationPx = (int) 10;
            @Override
            public void run() {
                int newY = planet.getY() + (up ? -1 : 1);
                int newX = planet.getX() + (left ? -1 : 1);
                up = (newY < initialY - maxAnimationPx) ? false : (newY > initialY + maxAnimationPx) ? true : up;
                left = (newX < initialX - maxAnimationPx) ? false : (newX > initialX + maxAnimationPx) ? true : left;
                planet.setLocation(newX, newY);
            }
        }, 0, 100);
        return t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        lblDistance2 = new javax.swing.JLabel();
        ImgAsteroid = new javax.swing.JLabel();
        ImgEarth = new javax.swing.JLabel();
        lblAsteroidName = new javax.swing.JLabel();
        lblAsteroidDistance = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDetailName = new javax.swing.JLabel();
        lblDetailDiameter = new javax.swing.JLabel();
        lblDetailMagnitude = new javax.swing.JLabel();
        lblDetailOrbit = new javax.swing.JLabel();
        lblDetailVelocity = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        lblDistance2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblDistance2.setForeground(new java.awt.Color(255, 255, 255));
        lblDistance2.setText("EARTH");
        jPanel2.add(lblDistance2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        ImgAsteroid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/viandwi24/asteroidguard/assets/100.png"))); // NOI18N
        jPanel2.add(ImgAsteroid, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 90, 90));

        ImgEarth.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/viandwi24/asteroidguard/assets/planet-13.png"))); // NOI18N
        jPanel2.add(ImgEarth, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 230, 220));

        lblAsteroidName.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAsteroidName.setForeground(new java.awt.Color(255, 255, 255));
        lblAsteroidName.setText("XXX");
        jPanel2.add(lblAsteroidName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        lblAsteroidDistance.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAsteroidDistance.setForeground(new java.awt.Color(255, 255, 255));
        lblAsteroidDistance.setText("1.000 KM");
        jPanel2.add(lblAsteroidDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(104, 24, 141));

        lblDetailName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDetailName.setForeground(new java.awt.Color(255, 255, 255));
        lblDetailName.setText("Asteroid Name : XXX");

        lblDetailDiameter.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDetailDiameter.setForeground(new java.awt.Color(255, 255, 255));
        lblDetailDiameter.setText("Diameter : 10KM");

        lblDetailMagnitude.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDetailMagnitude.setForeground(new java.awt.Color(255, 255, 255));
        lblDetailMagnitude.setText("Magnitude : 12.00");

        lblDetailOrbit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDetailOrbit.setForeground(new java.awt.Color(255, 255, 255));
        lblDetailOrbit.setText("Orbitting Body : Earth");

        lblDetailVelocity.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblDetailVelocity.setForeground(new java.awt.Color(255, 255, 255));
        lblDetailVelocity.setText("Velocity CP : 8.13km/s");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Detail");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDetailVelocity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDetailOrbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDetailMagnitude, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDetailName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(lblDetailDiameter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(lblDetailName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetailDiameter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetailMagnitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetailOrbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDetailVelocity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 230, 160));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/viandwi24/asteroidguard/assets/background_space.png"))); // NOI18N
        jPanel2.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AsteroidTracker win = new AsteroidTracker();
        win.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AsteroidInformationDetail win = new AsteroidInformationDetail(this.asteroid);
        win.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsteroidInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsteroidInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsteroidInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsteroidInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsteroidInformation(new JSONObject()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ImgAsteroid;
    private javax.swing.JLabel ImgEarth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAsteroidDistance;
    private javax.swing.JLabel lblAsteroidName;
    private javax.swing.JLabel lblDetailDiameter;
    private javax.swing.JLabel lblDetailMagnitude;
    private javax.swing.JLabel lblDetailName;
    private javax.swing.JLabel lblDetailOrbit;
    private javax.swing.JLabel lblDetailVelocity;
    private javax.swing.JLabel lblDistance2;
    // End of variables declaration//GEN-END:variables
}
